import nextEnv from "@next/env"; nextEnv.loadEnvConfig(process.cwd());
const { createJiti } = await import("jiti"); const jiti = createJiti(import.meta.url, { alias: { "@": process.cwd() + "/src" } });
const { adminDb } = await jiti.import("./src/lib/firebase-admin.ts");
const R = await jiti.import("./src/lib/reviews.ts");
const id = "test_review_" + Date.now(); const token = R.newToken();
await adminDb.collection("orders").doc(id).set({ stripe_id: id, test: true, deleted: false, amount_total: 8000, payment_status: "paid", created: Math.floor(Date.now()/1000), customer_email: "test@example.com", customer_name: "Test Kişi", locale: "de", shipping_details: { name: "Test Kişi", city: "Berlin", country: "DE" }, line_items: [{ description: "Konya Tişört - siyah, M", quantity: 1, amount_total: 4000 }, { description: "Şanlıurfa Tişört - beyaz, L", quantity: 1, amount_total: 4000 }], review_token: token });
const base = "http://localhost:3130";
const g = await (await fetch(`${base}/api/reviews?token=${token}`)).json(); console.log("review form:", JSON.stringify(g));
const p1 = await fetch(`${base}/api/reviews`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ token, name: "Test K.", reviews: [{ slug: "konya", rating: 5, text: "Sehr gute Qualität" }, { slug: "rize", rating: 1, text: "not bought" }] }) });
console.log("submit:", p1.status, JSON.stringify(await p1.json()));
const p2 = await fetch(`${base}/api/reviews`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ token, reviews: [{ slug: "konya", rating: 4 }] }) });
console.log("second submit:", p2.status, JSON.stringify(await p2.json()));
const mine = (await R.allReviews()).filter(r => r.orderId === id); console.log("stored:", mine.map(r => `${r.slug} ${r.rating}★ ${r.status} "${r.text}" by ${r.name}`));
console.log("visible before approval:", (await (await fetch(`${base}/api/reviews?slug=konya`)).json()).count);
for (const r of mine) await R.setReviewStatus(r.id, "approved");
const shown = await (await fetch(`${base}/api/reviews?slug=konya`)).json(); console.log("visible after approval:", shown.count, shown.average, JSON.stringify(shown.reviews[0]));
const html = await (await fetch(`${base}/product/konya`)).text(); console.log("google stars in page:", /"aggregateRating"/.test(html), (html.match(/"ratingValue":[0-9.]+/) || [])[0]);
console.log("TOKEN", token, "ID", id);
process.exit(0);
